Repository canonical-web-and-design/vanillaframework.io, pull requests merged in 2018-06, with the labels that each got.

#130 Add event tracking to vf.io homepage
  index.html
Labels: Review: Code +1, Review: QA +1

#131 Update background hero image
  index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#132 Remove custom scss for button + link
  _sass/main.scss
  index.html
Labels: Review: Code +1, Review: Design +1, Review: UX +1

#134 Added snap logo and fixed logo class
  _sass/main.scss
  index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#135 Update Twitter social link
  index.html
Labels: Review: Code +1, Review: QA +1
