Repository canonical-web-and-design/vanillaframework.io, pull requests merged in 2019-10, with the labels that each got.

#252 Remove trailing forward slashes and redirected www. subdomains from all links
  _includes/header.html
  accessibility.html
  contribute.html
  index.html
  showcase.html
Labels: Review: Code needed, Review: QA needed

#251 Reordered head tags
  _includes/head.html
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#250 Fix URL in sw.js
  sw.js
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#256 Update 404 template
  404.html
Labels: Review: Code +1, Review: QA +1

#257 Update 500 template
  500.html
  _sass/main.scss
Labels: Review: Code +1, Review: QA +1

#259 Upgrade vanilla framework to 2.4.1 and update references
  index.html
  package.json
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#260 Update logo examples
  index.html
Labels: Review: Code +1, Review: QA +1

#261 Add blog feeds section
  index.html
Labels: Review: Code +1, Review: QA +1

#263 Fix blog button padding
  index.html
Labels: Review: Code +1, Review: QA +1

#264 Update docker image to bionic
  Dockerfile
Labels: Review: Code +1, Review: QA +1
