Repository canonical-web-and-design/vanillaframework.io, pull requests merged in 2019-09, with the labels that each got.

#241 Update to vanilla 2.4
  _includes/header.html
  index.html
  package.json
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#240 Reduce size and add alt tags to images
  index.html
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#242 Update syntax-highlight to improve accessibility measure
  _sass/_patterns_syntax-highlight.scss
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#244 Remove coding standards page
  _includes/header.html
  coding-standards.html
Labels: Review: Code +1, Review: QA +1

#243 Update content on /contribute page
  contribute.html
Labels: Review: Code +1, Review: QA +1

#245 Update content on /browser-support page
  browser-support.html
Labels: Review: Code +1, Review: QA +1

#246 Update content on /accessibility page
  accessibility.html
Labels: Review: Code +1, Review: QA +1

#247 Update content on /homepage
  _sass/main.scss
  index.html
Labels: Review: Code +1, Review: QA +1

#249 Update content on /showcase
  showcase.html
Labels: Review: Code +1, Review: QA +1
