Repository canonical-web-and-design/vanillaframework.io, pull requests merged in 2019-06, with the labels that each got.

#218 Update homepage link to v2.0.0
  index.html
Labels: Review: Code +1, Review: QA +1

#212 Upgrade vanilla 2.0.0
  404.html
  _includes/footer.html
  _includes/header.html
  _sass/_patterns_icons.scss
  accessibility.html
  coding-standards.html
  contribute.html
  index.html
  package.json
  showcase.html
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#229 Update Juju logo to JAAS
  index.html
Labels: Review: Code +1, Review: QA +1

#227 Update bugs content list
  browser-support.html
Labels: Review: Code needed, Review: QA needed

#226 Add new contributor to the team
  contribute.html
Labels: Review: Code needed, Review: QA needed

#230 Update local development instructions
  contribute.html
Labels: Review: Code +1, Review: QA +1

#228 Update Downloads section
  index.html
Labels: Review: Code +1, Review: QA +1
